### ISSUE TITLE
Support CC, BCC & ReplyTo

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/ruby-sparkpost#2]
Support CC, BCC, ReplyTo etc. in Transmission.

**Comment by rajumsys** [comment]
I'm going to start this one

**Comment by szymonbaranowski** [comment]
@rajumsys any progress with this one so far?

**Comment by richleland** [comment]
Due to incredible support and contributions from the community, we discontinued support of the official SparkPost ruby client library as of May 17, 2016. If you’re looking for an alternative, take a look at some of [these repositories](https://github.com/search?l=Ruby&q=sparkpost&type=Repositories&utf8=%E2%9C%93).
