### ISSUE TITLE
Unique exception classes

### ISSUE THREAD

**Issue by benjaminwood** [SparkPost/ruby-sparkpost#44]
For example, these two exceptions are completely different, yet they share the same exception class.

```
SparkPost::DeliveryException: [{"message"=>"Exceed Sending Limit (daily)", "code"=>"2102"}]
```

Vs

````
SparkPost::DeliveryException: [{"message"=>"transmission created, but with validation errors", "code"=>"2000"}]
```

Perhaps these could use exception classes like `SparkPost::SendingLimitExceed` and `SparkPost::ValidationFailed`. Thoughts on this?

**Comment by rajumsys** [comment]
Our delivery exceptions aren't very specific to what's happening. There is a ticket to handle the 2nd one ( #14 ).

**Comment by richleland** [comment]
Due to incredible support and contributions from the community, we discontinued support of the official SparkPost ruby client library as of May 17, 2016. If you’re looking for an alternative, take a look at some of [these repositories](https://github.com/search?l=Ruby&q=sparkpost&type=Repositories&utf8=%E2%9C%93).
